version: "4.0"

services:
  unisco_app:
    build:
      context: .
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    environment:
      - FLASK_DEBUG=true
      - FLASK_ENV=development      
    working_dir: /app
    command: python app.py
    profiles:
      - dev

  unisco_app_prod:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=false
      - FLASK_ENV=production         
    command: python app.py
    profiles:
      - prod
